import:
  - ~/.config/alacritty/ayu_dark.yaml

window:
  dimensions:
    columns: 100
    lines: 30
  padding:
    x: 10
    y: 10
  decorations: full
  dynamic_padding: true
  opacity: 0.80

shell:
  program: /usr/bin/zsh

font:
  normal:
    family: JetBrainsMono Nerd Font
    style: Regular
  bold:
    family: JetBrainsMono Nerd Font
    style: Bold
  italic:
    family: JetBrainsMono Nerd Font
    style: Italic
  bold_italic:
    family: JetBrainsMono Nerd Font
    style: Bold Italic
  size: 12
  draw_bold_text_with_bright_colors: true

key_bindings:
  - { key: N, mods: Command, action: SpawnNewInstance }
  - { key: Space, mods: Alt, chars: " " }
  - { key: Back, mods: Super, chars: "\x15" } # delete word/line
  - { key: Left, mods: Alt, chars: "\x1bb" } # one word left
  - { key: Right, mods: Alt, chars: "\x1bf" } # one word right
  - { key: Left, mods: Command, chars: "\x1bOH", mode: AppCursor } # Home
  - { key: Right, mods: Command, chars: "\x1bOF", mode: AppCursor } # End
  - { key: R, mods: Command, chars: "\x1bR" }
